### ISSUE TITLE
Any updates on a release with recent changes

### ISSUE THREAD

**Issue by mckenzieFullStory** [hairyhenderson/go-codeowners#16]
Terribly sorry for the bother, and I really dislike it when folks ask this, but is there any plans for a release with some of the new changes (like PR #10) to the API here?

**Comment by hairyhenderson** [comment]
Sorry for the delay... Release coming soon, after #19 is merged.

**Comment by hairyhenderson** [comment]
See https://github.com/hairyhenderson/go-codeowners/releases/tag/v0.3.0
