### ISSUE TITLE
Mistmatch in releases

### ISSUE THREAD

**Issue by pablochacin** [hairyhenderson/go-codeowners#40]
The [package documentation](https://pkg.go.dev/github.com/hairyhenderson/go-codeowners@v0.5.0#section-readme) refers to version `v0.5.0` (Jun 2024) but the [repository lists ](https://github.com/hairyhenderson/go-codeowners/releases)`v0.4.0` (july 2023) as the latest relase

**Comment by hairyhenderson** [comment]
(I've created the release now)
